- Example/Tests/Configuration.swift
- Example/Tests/IdentityManagerTests.swift
- Example/Tests/UserTests.swift
- SchibstedAccount/Manager/IdentityManager.swift
- SchibstedAccount/Manager/User/User.swift
> Fix user tokens not cleared on logout if `IdentityManager` is not available

- SchibstedAccount.xcodeproj/project.pbxproj
- Source/UI/Coordinators/CompleteProfileCoordinator.swift
- Source/UI/Coordinators/ShowTermsCoordinator.swift
- Source/UI/Coordinators/UpdatedTermsCoordinator.swift
- Source/UI/IdentityUI.swift
Add a `ShowTermsCoordinator` that is used by both `CompleteProfileCoordinator` and `UpdatedTermsCoordinator`. This was originally intended for #56, but might be useful regardless, as it should make changing the terms screen simpler by providing it from a single place.
> Refactor: add common ShowTermsCoordinator

- Source/UI/IdentityUI.swift
This is so that if the UIFlow is dismissed without `didFinish` being
called, there is no retain cycle
> Make the statics that hold on to UI processes weak

- Source/UI/IdentityUI.swift
Make `updatedTermsCoordinator` a strong reference and handle the case of the client dismissing the view controller outside of the SDK control by subclassing `UINavigationController` and introducing a new `didDismiss` callback.
Closes #104.
> Fixed: blank screen when updating terms

- Source/UI/IdentityUI.swift
By intercepting viewDidDisappear and firing a completion with `.cancel` result in case the client dismissed the UI out of the SDK control.
> Handle premature dismissal of Identity UI

- Source/UI/IdentityUI.swift
onlyDimiss doesn't call the delegate completion callback, and it
doesn't look like we need it
> Fixed aborting flow to call the cancel instead of "onlyDismiss"

- Source/UI/Screens/Identifier/IdentifierViewController.swift
- Source/UI/Screens/Password/PasswordViewController.swift
Sets the `textContentType` on the username and password text fields.
This enables us to utilize the autofill function provided by Apple as seen at [WWDC 2017](https://developer.apple.com/videos/play/wwdc2017/206/).
> Added: Adds support for username/password autofill

- Source/Manager/SwiftKeychain.swift
- Tests/UserTokensKeychainTests.swift
**Problem**
If a killed app receives a push notifications with `content-available` set to `1`, and the app allows background mode, the app will be launched in the background by the system. 
If the device is locked when this happens - reads to keychain values with  `kSecAttrAccessibleWhenUnlocked` will fail with an error `Access to item attempted while keychain is locked.`.
If the app is relying on the state of the User logged in state as part of the launch of the app - that state will then signal that there are no access tokens stored, meaning the user is signed out.
We've been experiencing this problem at Blocket with users getting signed out, as they receive push notifications for messages.
**Proposed solution**
Rather than storing values to only be read while the device is unlocked, …
> Changed: Store tokens with accessmode kSecAttrAccessibleAfterFirstUnlock to allow background access.

- Source/Core/SynchronizedDictionary.swift
- Source/Core/SynchronizedWeakDictionary.swift
- Source/Manager/User/User.swift
Some clients use headless and visual login. This is necessary if
you want to implemente web credentials for e.g. since it's not
supported in the visual login flow.
So there could be multiple User instances in the global store if
logins occur via different methods (visual and headless) and if
there're any User objects lying around.
This patch just makes sure all the other User instance's tokens
are clearned if any one User instance calls logout
> Logout all similar users in global store

- Source/Manager/TaskManager/TaskManager.swift
- Source/Manager/TaskManager/TaskOperation.swift
Seems like that was handled by accident only because we would
check isCancelled is TaskOperation.start
> Fixed: cancellation of tasks to "finish" an NSOperation

- Source/Manager/TaskManager/TaskManager.swift
- Source/Manager/TaskManager/TaskOperation.swift
This reverts commit 13f59212cf0902255f35212ce6e757e540fee074.
This seems to be causing problems locally. I think that PR probably needs a bit more work before it's ok.
> Revert "Fixed: cancellation of tasks to "finish" an NSOperation"

- Source/Manager/Protocols/UserAuthAPI.swift
- Source/Manager/SDKConfiguration/SDKConfiguration.swift
- Source/Manager/TaskManager/TaskManager.swift
- Source/Manager/User/User+Auth.swift
- Tests/AutoRefreshURLProtocolTests.swift
- Tests/Configuration.swift
- Tests/URLSessionTests.swift
- Tests/Utils/TestingUser.swift
Since this change is backwards incompatible, it'll go into version 2.0 (skipping deprecation, then removal as in #224).
> Changed: Move token refresh retry limit to SDKConfiguration.

- Source/Core/EventEmitter.swift
- Source/Core/Networking/StubbedNetworkingProxy.swift
- Source/Manager/TaskManager/OwnedTaskHandle.swift
Due to new rule (legacy_hashing) introduced in [swiftlint 0.29.2](https://github.com/realm/SwiftLint/pull/2496).
> Switch to using hash(into:) instead of hashValue from Hashable.

- README.md
- Source/UI/Coordinators/PasswordCoordinator.swift
- Source/UI/IdentityUIConfiguration.swift
Add a configuration option `enableBiometrics` for clients to enable/disable Biometric login. Note that this is different from `useBiometrics` which holds the user's choice with regard to Biometrics.
> Add a configuration option for clients to enable/disable touch ID

- Source/Manager/IdentityAPI/IdentityAPI.swift
- Source/Manager/IdentityAPI/Router.swift
- Source/Manager/User/User.swift
- Tests/IdentityAPITests.swift
- Tests/UserTests.swift
The endpoint currently does nothing and will be deprecated.
> Don't call /api/2/logout endpoint on user logout.

- Source/UI/Screens/Identifier/IdentifierViewController.swift
- Source/UI/Screens/Identifier/IdentifierViewController.xib
This shows up in the UI as grey background where the content view
doesn't cover it.
> Don't round the corners of the content view in IdentifierViewController.

- Gemfile.lock
This should replace 2.3.0:
- Enable face ID.
- Code & dev updates for Xcode 10.2
- Fix some pods linting warnings.
> Release 2.3.1

- Source/Core/Networking/Result.swift
- Source/UI/Coordinators/CompleteProfileCoordinator.swift
There's no need for a custom result type, and this avoids conflicting types in clients that integrate the SDK.
> Replace SchibstedAccount.Result with Swift.Result

- Source/Manager/ClientConfiguration.swift
- Source/Manager/User/User.swift
- Source/Manager/UserTokensKeychain.swift
- Source/Manager/UserTokensStorage.swift
In order to use a shared keychain, apps need to be able to set the `accessGroup` property on the `UserTokensKeychain` in order for it to be used in the attributes passed to `SecItemAdd` in the `SPiDKeychainWrapper`.
This will allow shared authentication between apps on the same Apple team.
> Added: Allow passing keychain access group to the UserTokensKeychain attributes

- Source/Core/SynchronizedDictionary.swift
- Source/UI/IdentityUI.swift
- Source/UI/IdentityUIViewController.swift
- Source/UI/Screens/CheckInbox/CheckInboxViewController.xib
- Source/UI/Screens/Error/ErrorViewController.xib
- Source/UI/Screens/Identifier/IdentifierViewController.xib
- Source/UI/Screens/Info/InfoViewController.xib
- Source/UI/Screens/Password/PasswordViewController.xib
- Source/UI/Screens/RequiredFields/RequiredFieldsViewController.xib
- Source/UI/Screens/Resend/ResendViewController.xib
- Source/UI/Screens/Terms/TermsViewController.xib
- Source/UI/Screens/Verify/VerifyViewController.xib
- Source/UI/Style/StyleIcons.swift
- Source/UI/Views/LogoView.swift
#309 missed a few cases of `Bundle` usage for resources, which should use `Bundle.module` when targeting the SPM package.
I also had to remove `customModuleProvider="target"` from all the .xib files in order to ensure correct module targeting.
> Changed: Fixed incorrect bundle usage in the SwiftPM package

- Source/Manager/LegacySPiDAccessToken/SPiDAccessToken.swift
- Source/Manager/LegacySPiDAccessToken/SPiDKeychainWrapper.swift
> Fix deserialisation of legacy storage format for token data.

- Example/PasswordFlowViewController.swift
- Source/Manager/IdentityManager.swift
- Source/Manager/IdentityManagerOverloads.swift
- Source/Manager/Protocols/IdentityManagerProtocol.swift
- Source/UI/Coordinators/PasswordCoordinator.swift
- Source/UI/IdentityUIConfiguration.swift
- Source/UI/Interactors/SigninInteractor.swift
This will give the user the option to save the username & password in the shared web credentials, so they can easily login on the related websites as well.
The user will be prompted _once_ with the following:
and when logging in with a different/updated password:
> Save the username & password to the shared web credentials

- Source/UI/IdentityUIViewController.swift
This ensures the keyboard appearance notifications will be correctly delivered.
> Call `view.endEditing(true)` before setting isUserInteractionEnabled to false
