schibsted/account-sdk-ios

Example/AppDelegate.swift, Example/StatusViewController.swift, Source/Core/Networking/DefaultNetworkingProxy.swift, Source/Core/Networking/NetworkingHeaders.swift, Source/Core/Networking/StubbedNetworkingProxy.swift, Source/Manager/Identifiers/Identifier.swift, Source/Manager/User/URLSession+User.swift, Source/UI/IdentityUIRoute.swift, Tests/AutoRefreshURLProtocolTests.swift, Tests/Configuration.swift, Tests/IdentityAPITests.swift, Tests/Utils/TestingNetworkingProxy.swift
=> Added: xOIDC header for internal requests

Source/UI/IdentityUI.swift, Source/UI/IdentityUIConfiguration.swift
=> ADDED: presentationHook block to IdentityUIConfiguration

Source/UI/Resources/en.lproj/Localizable.strings, Source/UI/Screens/RequiredFields/RequiredFieldsViewController.swift, Source/UI/Screens/RequiredFields/RequiredFieldsViewController.xib, Source/UI/Screens/Terms/TermsViewController.xib, Source/UI/Views/TextView.swift
Use a text view instead of a label since it will need to handle links.
Closes #59.
=> Update copy in required fields screen

Source/UI/Screens/Password/PasswordViewController.swift
=> dont limit login password to 8 chars

Source/UI/Screens/Password/PasswordViewController.swift, Source/UI/Screens/Verify/VerifyViewController.swift
=> Fixed: title on whatsThis button

Example/AppDelegate.swift
=> Fixed: example app webClientID config

Tests/URLSessionTests.swift
This reverts commit b8edd26ba5906c180fda8af1ece08826d86337cd.
=> Revert "might be something wrong with the url stub path"

Source/UI/Resources/en.lproj/Localizable.strings
=> Update English copies

Source/UI/Screens/Identifier/IdentifierViewController.swift, Source/UI/Screens/Password/PasswordViewController.swift, Source/UI/Screens/RequiredFields/RequiredFieldsViewController.swift, Source/UI/Screens/RequiredFields/RequiredFieldsViewModel.swift, Source/UI/Screens/Terms/TermsViewController.swift, Source/UI/Screens/Verify/VerifyViewController.swift, Source/UI/Tracking/TrackingEventsHandler.swift
Implements the changes described [here](https://github.schibsted.io/spt-dataanalytics/pulse-monitor-ui/pull/463/files).
Related to the changes in the tracking pod implemented [here](https://github.schibsted.io/spt-identity/identity-sdk-ios-tracking/compare/update-tracking) that need to be merged after this PR is merged.
Closes #61.
=> Update tracking to the latest specs

Source/UI/Screens/Identifier/IdentifierViewController.swift, Source/UI/Screens/Identifier/IdentifierViewController.xib, Source/UI/Views/LogoView.swift
=> Fixed: auto layout bullshit

Source/UI/IdentityUIViewController.swift
=> Added: keyboard dismissal by tapping outside of the text fields

Source/Manager/User/User.swift, Source/UI/Coordinators/AuthenticationCoordinator.swift, Source/UI/Coordinators/PasswordCoordinator.swift, Source/UI/Coordinators/PasswordlessCoordinator.swift, Source/UI/IdentityUI.swift, Source/UI/Interactors/OneTimeCodeInteractor.swift, Source/UI/Interactors/SigninInteractor.swift
=> Fixed: Persist user tokens only after login process is complete

Source/UI/IdentityUI.swift
Use an assertion instead and log the error too
=> Changed: don't crash if precondition fails in presenting UI

Source/UI/Screens/Error/ErrorViewController.xib
Fixes issue https://github.com/schibsted/account-sdk-ios/issues/130
=> Fix: Issue 130

Source/Manager/IdentityAPI/Models/UserProfile.swift, Tests/Responses/user-profile-valid.json, Tests/UserProfileSessionTests.swift
The primary email in the list of emails is not always there. This
one is more guaranteed to be there always I think
Fixes #15
=> Added email to user profile

Source/UI/IdentityUITheme.swift, Source/UI/Screens/Error/ErrorViewController.swift, Source/UI/Screens/Identifier/IdentifierViewController.swift, Source/UI/Screens/Info/InfoViewController.swift, Source/UI/Screens/Info/InfoViewController.xib, Source/UI/Screens/RequiredFields/RequiredFieldsViewController.swift, Source/UI/Screens/Resend/ResendViewController.swift, Source/UI/Screens/TermsSummary/TermsSummaryViewController.swift, Source/UI/Views/TextField.swift
=> Fixed corner radius theming

Example/Assets.xcassets/Contents.json, Source/UI/Screens/Password/PasswordViewController.xib, Source/UI/Screens/Terms/TermsViewController.xib, Source/UI/Views/Checkbox.swift
=> Fixed: custom image checkbox scaling

Source/UI/Coordinators/FlowCoordinator.swift
=> Fixed: make the webview controls match tint colors of icons in theme

Source/UI/IdentityUITheme.swift, Source/UI/Screens/Password/PasswordViewController.swift, Source/UI/Screens/Password/PasswordViewController.xib, Source/UI/Screens/Resend/ResendViewController.swift, Source/UI/Screens/Resend/ResendViewController.xib, Source/UI/Style/StyleColors.swift, Source/UI/Views/PrimaryButton.swift
It should be collapsed if you're in a create account flow
Fixes #144
=> Fixed: forgot password in create user flow

Source/UI/IdentityUITheme.swift, Source/UI/Views/TextField.swift
=> Added: ability to set default clear text field image

Example/AppDelegate.swift, Source/UI/Coordinators/FlowCoordinator.swift
=> Fixed: webview transition artifacts on formsheet presentation

Example/AppDelegate.swift, Example/StatusViewController.swift, Source/UI/IdentityUI.swift, Source/UI/IdentityUIConfiguration.swift, Source/UI/IdentityUIDelegate.swift, Source/UI/Resources/en.lproj/Localizable.strings, Source/UI/Resources/fi.lproj/Localizable.strings, Source/UI/Resources/nb.lproj/Localizable.strings, Source/UI/Resources/sv.lproj/Localizable.strings, Source/UI/Screens/Identifier/IdentifierViewController.swift, Source/UI/Screens/Identifier/IdentifierViewController.xib, Source/UI/Screens/Identifier/IdentifierViewModel.swift
=> Added: skip button to UI with delegate to control

Example/AppDelegate.swift, Source/UI/IdentityUI.swift
The interplay between the delegates has been a source of bugs on
multiple occasions.
Fixes #135
=> Deperate IdentityUI init that takes an IdentityManager

Example/AppDelegate.swift, Example/ProfileViewController.swift, Example/StatusViewController.swift, Example/TermsAgreementsViewController.swift, Example/TokenExchangeViewController.swift, Source/Manager/Identifiers/Identifier.swift, Source/Manager/Identifiers/PhoneNumber.swift, Source/Manager/IdentityAPI/Models/UserProfile.swift, Source/Manager/User/User.swift, Source/Manager/UserTokensKeychain.swift, Source/Manager/UserTokensStorage.swift, Source/UI/IdentityUI.swift, Source/UI/Screens/Identifier/IdentifierViewController.swift, Tests/IdentifierTests.swift
* Added phone number field to UserProfile
* And updates Example app which resulted in slight changes to User keychain loading/unloading
=> Phone number AND user loading adjustments

Source/Manager/User/User.swift
We were clearning even if there were no new tokens to set so the
old keychain tokens would go baboom
=> Fixed: setting new user tokens

Source/Manager/ClientError.swift, Source/UI/ClientError+localized.swift, Source/UI/Resources/en.lproj/Localizable.strings, Source/UI/Resources/fi.lproj/Localizable.strings, Source/UI/Resources/nb.lproj/Localizable.strings, Source/UI/Resources/sv.lproj/Localizable.strings, Source/UI/Screens/Password/PasswordViewController.swift, Source/UI/Screens/Password/PasswordViewModel.swift, Source/UI/Screens/RequiredFields/RequiredFieldsViewModel.swift, Source/UI/Screens/RequiredFields/SupportedRequiredField.swift
Refs https://github.com/schibsted/account-sdk-ios/issues/190
Refs https://github.com/schibsted/account-sdk-ios/issues/133
=> Fixed: 133 & 190

.jazzy.yaml, SchibstedAccount.podspec, Source/UI/Screens/Verify/VerifyViewController.swift, scripts/populate-dummy-secrets.sh
Merging `stable-1.1.x` branch into `master` in preparation for only having one long-lived branch (which will be `master`).
=> Prepare 2.0

Source/Manager/IdentityAPI/IdentityAPI.swift
Replaces #239 (for Travis tests to run properly).
=> Add retry on network error

Source/Manager/IdentityAPI/IdentityAPI.swift
=> Changed: Retry network calls also on ECONNABORTED.

Example/Base.lproj/Main.storyboard, Example/StatusViewController.swift, README.md, Source/InfoPlist.strings, Source/UI/Coordinators/PasswordCoordinator.swift, Source/UI/IdentityUIConfiguration.swift, Source/UI/Resources/en.lproj/Localizable.strings, Source/UI/Resources/fi.lproj/Localizable.strings, Source/UI/Resources/nb.lproj/Localizable.strings, Source/UI/Resources/sv.lproj/Localizable.strings, Source/UI/Screens/Password/PasswordViewModel.swift
Implement finger ID as authentication method in the new Identity flows for iOS
=> ID-2824: add biometric login

SchibstedAccount.podspec, Source/Core/Version.swift, Source/Info.plist
* Bug & security fixes:
* Fix some vulnerable packages in the rubygems dependencies of this project.
* New features:
* Prefill the user email by default.
* Update Schibsted logo.
=> Release 2.4.0

Source/UI/Coordinators/PasswordCoordinator.swift, Source/UI/Tracking/TrackingEventsHandler.swift
Also include which type of biometric authentication was used (TouchID
or FaceID).
=> Emit tracking event when the user logs in using biometrics.

SchibstedAccount.xcodeproj/project.pbxproj, Source/UI/Resources/Images.xcassets/password-hide.imageset/Contents.json, Source/UI/Resources/Images.xcassets/password-hide.imageset/password-hide.pdf, Source/UI/Resources/Images.xcassets/password-show.imageset/Contents.json, Source/UI/Resources/Images.xcassets/password-show.imageset/password-show.pdf, Source/UI/Screens/Password/PasswordViewController.swift, Source/UI/Screens/Password/PasswordViewController.xib, Source/UI/Style/StyleIcons.swift, Source/UI/Style/UIImage+Style.swift, Source/UI/Utils/Utils.swift, Source/UI/Views/PasswordTextField.swift, Source/UI/Views/TextField.swift
✅ ~TODO: the show/hide password icons are currently to small and should be scaled up (to match other icon's size).~
=> Fix #289: Add "show password" toggle.

Example/Base.lproj/Main.storyboard, Example/StatusViewController.swift, Source/Manager/IdentityAPI/Models/IDToken.swift, Source/Manager/IdentityAPI/Models/TokenData.swift, Source/Manager/User/User+load.swift, Source/Manager/User/User.swift
Logic required for app transfer
=> 1325-app transfer logic
